name: chip8-swing

on: [push]

jobs:
  verify:

    runs-on: ubuntu-latest

    steps:
    # temporary checkout and build of core dependency
    - name: git core
      uses: actions/checkout@v2
      with:
        path: core
        repository: metteo/chip8-core
        token: ${{ secrets.GitHub_PAT }}

    - name: maven core
      uses: "xlui/action-maven-cli/jdk11@master"
      with:
        args: -B -Dmaven.repo.local=$PWD/repo clean install --file core/pom.xml

    - name: git swing
      uses: actions/checkout@v2
      with:
        path: swing

    - name: maven swing
      uses: "xlui/action-maven-cli/jdk11@master"
      with:
        args: -B -Dmaven.repo.local=$PWD/repo clean verify --file swing/pom.xml
